# Generated by Django 2.2.5 on 2019-09-30 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutBattleField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_room', models.CharField(max_length=20)),
                ('about_room', models.TextField(max_length=56)),
                ('image_room', models.ImageField(upload_to='battlefield_media')),
            ],
        ),
        migrations.CreateModel(
            name='BattleFieldContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg_room', models.ImageField(upload_to='battlefield_media')),
            ],
        ),
    ]
